---
version: '3.8'

services:
  # Data Download Services
  # telegram-watcher:
  #   build: ./data-download/telegram-watcher
  #   environment:
  #     - TELEGRAM_API_ID=${TELEGRAM_API_ID}
  #     - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
  #     - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - bp-network

  # telegram-downloader:
  #   build: ./data-download/telegram-downloader
  #   environment:
  #     - TELEGRAM_API_ID=${TELEGRAM_API_ID}
  #     - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - bp-network

  # archive-parser:
  #   build: ./data-download/archive-parser
  #   depends_on:
  #     - opensearch-node1
  #     - opensearch-node2
  #   networks:
  #     - bp-network

  # Data Storage Services
  #postgres:
  #  image: docker.io/library/postgres:latest
  #  environment:
  #    - POSTGRES_USER=${POSTGRES_USER}
  #    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #    - POSTGRES_DB=${POSTGRES_DB}
  #  volumes:
  #    - postgres_data:/var/lib/postgresql/data
  #  networks:
  #    - bp-network

  opensearch-node1:
    build: ./opensearch
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - bp-network

  opensearch-node2:
    build: ./opensearch
    container_name: opensearch-node2
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node2
      - discovery.seed_hosts=opensearch-node1,opensearch-node2
      - cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
    networks:
      - bp-network

  opensearch-dashboards:
    image: docker.io/opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
    networks:
      - bp-network

  # GUI Service
  #web-app:
  #  build: ./gui
  #  ports:
  #    - "5000:5000"
  #  depends_on:
  #    - postgres
  #    - opensearch-node1
  #    - opensearch-node2
  #  networks:
  #    - bp-network

  # Domain Watcher Services
  # domain-watcher:
  #   build: ./domain-watcher
  #   depends_on:
  #     - postgres
  #     - opensearch-node1
  #     - opensearch-node2
  #   networks:
  #     - bp-network

  # mail-server:
  #   image: mailhog/mailhog
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - bp-network

networks:
  bp-network:
    driver: bridge

volumes:
  postgres_data:
  opensearch-data1:
  opensearch-data2: 