"""Divide and conquer into files

Revision ID: 0034e8008d45
Revises: 7c1685536c18
Create Date: 2025-04-15 00:20:45.319961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0034e8008d45'
down_revision = '7c1685536c18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index('ix_alert_domain_id')

    op.drop_table('alert')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('is_new', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('domain_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index('ix_alert_domain_id', ['domain_id'], unique=False)

    # ### end Alembic commands ###
