"""Divide and conquer into files

Revision ID: 107ad643fc75
Revises: 0034e8008d45
Create Date: 2025-04-15 00:25:55.293305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '107ad643fc75'
down_revision = '0034e8008d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False, comment='Alert ID'),
    sa.Column('is_new', sa.Boolean(), nullable=True, comment='Whether the alert is new or not'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Date and time the alert was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Date and time the alert was updated'),
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='Domain ID for which the alert was raised'),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Alerts are raised for specific domains'
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_domain_id'), ['domain_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_domain_id'))

    op.drop_table('alert')
    # ### end Alembic commands ###
