"""empty message

Revision ID: 7c1685536c18
Revises: 7c5c5ebadc20
Create Date: 2025-04-15 00:08:08.173027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c1685536c18'
down_revision = '7c5c5ebadc20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert',
    sa.Column('id', sa.Integer(), nullable=False, comment='Alert ID'),
    sa.Column('is_new', sa.Boolean(), nullable=True, comment='Whether the alert is new or not'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='Date and time the alert was created'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='Date and time the alert was updated'),
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='Domain ID for which the alert was raised'),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Alerts are raised for specific domains'
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_domain_id'), ['domain_id'], unique=False)

    op.create_table('watchlist_domain_association',
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('domain_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlist.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('watchlist_id', 'domain_id'),
    sa.UniqueConstraint('watchlist_id', 'domain_id', name='uq_watchlist_domain')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_domain_association')
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_domain_id'))

    op.drop_table('alert')
    # ### end Alembic commands ###
