"""Add watchlist, domain, alert tables

Revision ID: 7c5c5ebadc20
Revises: 
Create Date: 2025-04-14 23:05:22.105654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c5c5ebadc20'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False, comment='Domain ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Domain name'),
    sa.PrimaryKeyConstraint('id'),
    comment='Monitored domains'
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False, comment='Watchlist ID'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Watchlist name'),
    sa.Column('description', sa.Text(), nullable=True, comment='Watchlist description'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether the watchlist is active or not'),
    sa.Column('mail_address', sa.String(length=255), nullable=True, comment='Email address to send alerts to'),
    sa.Column('mail_alerts', sa.Boolean(), nullable=True, comment='Whether to send email alerts for this watchlist'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Watchlists are used to monitor domains'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist')
    op.drop_table('domain')
    # ### end Alembic commands ###
