"""add alert content

Revision ID: f1e8730e28d1
Revises: c3d21c1c45fb
Create Date: 2025-05-13 23:11:56.682946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1e8730e28d1'
down_revision = 'c3d21c1c45fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.JSON(), nullable=True, comment='Content of the alert'))

    with op.batch_alter_table('watchlist_domain_association', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_watchlist_domain', ['watchlist_id', 'domain_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist_domain_association', schema=None) as batch_op:
        batch_op.drop_constraint('uq_watchlist_domain', type_='unique')

    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
