"""Configuration of Celery for the Extractor."""
# Celery configuration generated by ChatGPT
# author: OpenAI
# title: ChatGPT
# medium: software
# version: GPT-4.0
# year: 2025
# prompt: How should I configure Celery? What does the task_queues and task_routes do? What about defining an Exchange?
# url: https://chatgpt.com/share/682252e1-7d74-8004-bf4a-c753104501df
# date: 2025-04-28

import os
from dotenv import load_dotenv
from kombu import Queue, Exchange
from kombu.abstract import Object

basedir = os.path.abspath(os.path.dirname(__file__))

load_dotenv(os.path.join(basedir, '.env'))

class ConfigUploader(Object):
    """Configuration class for uploader vhost."""
    broker_url = os.getenv("UPLOADER_BROKER_URL")

    # Declare named queues bound to direct exchanges
    task_queues = (
        Queue("uploads", Exchange("uploads", type="direct"), routing_key="uploads"),
    )

    # Route specific tasks to the appropriate queue
    task_routes = {
        "monitor.process_batch": {"queue": "uploads", "routing_key": "uploads"},
    }

    # auto-create any queue routed-to
    task_create_missing_queues = True

class ConfigDownloader(Object):
    """Configuration class for downloader vhost."""
    broker_url = os.getenv("DOWNLOADER_BROKER_URL")

    # Declare named queues bound to direct exchanges
    task_queues = (
        Queue("downloads", Exchange("downloads", type="direct"), routing_key="downloads"),
    )

    # Route specific tasks to the appropriate queue
    task_routes = {
        "extractor.extract_archive": {"queue": "downloads", "routing_key": "downloads"},
    }

    # auto-create any queue routed-to
    task_create_missing_queues = True