"""Configuration file for the Telegram Downloader Daemon."""
import os
from dotenv import load_dotenv
from kombu import Queue, Exchange

basedir = os.path.abspath(os.path.dirname(__file__))

load_dotenv(os.path.join(basedir, '.env'))

class Config(object):
    """Base configuration class."""
    # Telegram
    API_ID = os.getenv('TELEGRAM_API_ID')
    API_HASH = os.getenv('TELEGRAM_API_HASH')
    BOT_TOKEN = os.getenv('TELEGRAM_BOT_TOKEN')
    SESSION = 'downloader'
    # Logging
    LOGGING_FORMAT = '%(asctime)s Downloader: %(levelname)s: %(message)s'
    # Application
    WORKER_COUNT = 4
    DOWNLOAD_PATH = '/data'

# Celery configuration generated by ChatGPT
# author: OpenAI
# title: ChatGPT
# medium: software
# version: GPT-4.0
# year: 2025
# prompt: How should I configure Celery? What does the task_queues and task_routes do? What about defining an Exchange?
# url: https://chatgpt.com/share/682252e1-7d74-8004-bf4a-c753104501df
# date: 2025-04-28
class ConfigCelery(object):
    """Celery configuration class."""
    broker_url = os.getenv('CELERY_BROKER_URL')

    # Declare named queues bound to direct exchanges
    task_queues = (
        Queue('downloads', Exchange('downloads', type='direct'), routing_key='downloads'),
    )

    # Route specific tasks to the appropriate queue
    task_routes = {
        'extractor.extract_archive': {'queue': 'downloads', 'routing_key': 'downloads'},
    }

    # auto-create any queue routed-to
    task_create_missing_queues = True

    # seconds (5 minutes)
    broker_heartbeat = 300
